/**
 * Generating `solr.xml`, which is where backup repositories are declared.
 *
 * Three facts force this file to exist:
 *
 * 1. `<backup><repository>` is a **solr.xml** construct, not a solrconfig.xml
 *    one, so it cannot live in the configset that is already mounted.
 * 2. The stock `solr.xml` is written into `/var/solr` on first boot — inside the
 *    named volume that `docker compose down -v` destroys. Any repository
 *    configured by hand inside the container dies with it.
 * 3. Which repositories exist is a function of the tenant registry, and asking
 *    someone to keep hand-edited XML in step with a JSON registry is asking for
 *    the two to disagree.
 *
 * So: render from the registry, write to the host state directory, bind-mount it
 * in. Pure function, so the XML is testable without Docker.
 */
import type { ResolvedTenant, TenantRegistry } from "./tenancy.js";
import { DEFAULT_BACKUP_LOCATION, LOCAL_REPOSITORY_NAME } from "./tenancy.js";

export interface SolrXmlOptions {
	/**
	 * Container-side path the host backup directory is mounted at. Becomes the
	 * local repository's root, and must also appear in `solr.allowPaths`.
	 */
	localBackupPath?: string;
}

interface RepositoryDecl {
	name: string;
	type: "local" | "s3";
	/** Tenants served, for the generated comment — shared repositories are fine. */
	tenants: string[];
	bucket?: string;
	region?: string;
	endpoint?: string;
}

/**
 * Collapse the registry to the distinct repositories Solr must know about.
 *
 * Exported for the sake of the tools that report configuration: two tenants
 * pointed at one repository is legitimate, and worth being able to see.
 */
export function backupRepositories(
	registry: TenantRegistry,
	options: SolrXmlOptions = {},
): RepositoryDecl[] {
	const byName = new Map<string, RepositoryDecl>();

	// The local repository always exists, whether or not a tenant uses it. It is
	// the fallback every tenant resolves to when nothing else is declared, and a
	// missing repository fails BACKUP with a message about repository names
	// rather than about configuration.
	byName.set(LOCAL_REPOSITORY_NAME, {
		name: LOCAL_REPOSITORY_NAME,
		type: "local",
		tenants: [],
	});

	for (const tenant of registry.tenants) {
		const target = tenant.backup;
		const existing = byName.get(target.repository);

		if (existing) {
			assertCompatible(existing, tenant);
			existing.tenants.push(tenant.id);
			continue;
		}

		byName.set(target.repository, {
			name: target.repository,
			type: target.type,
			tenants: [tenant.id],
			...(target.s3
				? {
						bucket: target.s3.bucket,
						...(target.s3.region ? { region: target.s3.region } : {}),
						...(target.s3.endpoint ? { endpoint: target.s3.endpoint } : {}),
					}
				: {}),
		});
	}

	void options;
	return [...byName.values()];
}

/**
 * Two tenants may share a repository, but not disagree about what it is.
 *
 * Silently letting the first declaration win would mean a tenant's snapshots
 * going somewhere other than where its own configuration says — the kind of
 * divergence only noticed when a restore comes up empty.
 */
function assertCompatible(existing: RepositoryDecl, tenant: ResolvedTenant) {
	const target = tenant.backup;
	const sameType = existing.type === target.type;
	const sameBucket = existing.bucket === target.s3?.bucket;

	if (!sameType || (target.type === "s3" && !sameBucket)) {
		throw new Error(
			`Tenants ${[...existing.tenants, tenant.id].join(", ")} declare backup ` +
				`repository "${existing.name}" with different settings. A repository ` +
				"name means one storage location; give them distinct names or " +
				"identical settings.",
		);
	}
}

/**
 * Render the `solr.xml` Solr should boot with.
 *
 * Everything outside `<backup>` reproduces the stock defaults for SolrCloud —
 * omitting them would silently drop the shard handler and update processor
 * settings the image relies on.
 */
export function renderSolrXml(
	registry: TenantRegistry,
	options: SolrXmlOptions = {},
): string {
	const localPath = options.localBackupPath ?? DEFAULT_BACKUP_LOCATION;
	const repositories = backupRepositories(registry, options);

	const declarations = repositories
		.map((repo) => renderRepository(repo, localPath))
		.join("\n\n");

	return `<?xml version="1.0" encoding="UTF-8" ?>
<!--
  GENERATED by souk-compass from the tenant registry. Edits are overwritten on
  the next compass_setup start/initialize.

  Declare backup repositories by adding a "backup" block to a tenant in
  tenants.json, then restart Solr — repositories are read once, at boot.
-->
<solr>
  <str name="sharedLib">\${solr.sharedLib:}</str>
  <str name="allowPaths">\${solr.allowPaths:}</str>

  <solrcloud>
    <str name="host">\${host:}</str>
    <int name="hostPort">\${solr.port.advertise:0}</int>
    <str name="hostContext">\${hostContext:solr}</str>
    <bool name="genericCoreNodeNames">\${genericCoreNodeNames:true}</bool>
    <int name="zkClientTimeout">\${zkClientTimeout:30000}</int>
    <int name="distribUpdateSoTimeout">\${distribUpdateSoTimeout:600000}</int>
    <int name="distribUpdateConnTimeout">\${distribUpdateConnTimeout:60000}</int>
    <str name="zkCredentialsProvider">\${zkCredentialsProvider:org.apache.solr.common.cloud.DefaultZkCredentialsProvider}</str>
    <str name="zkACLProvider">\${zkACLProvider:org.apache.solr.common.cloud.DefaultZkACLProvider}</str>
  </solrcloud>

  <shardHandlerFactory name="shardHandlerFactory"
    class="HttpShardHandlerFactory">
    <int name="socketTimeout">\${socketTimeout:600000}</int>
    <int name="connTimeout">\${connTimeout:60000}</int>
  </shardHandlerFactory>

  <backup>
${declarations}
  </backup>
</solr>
`;
}

function renderRepository(repo: RepositoryDecl, localPath: string): string {
	const served =
		repo.tenants.length > 0
			? `serves: ${repo.tenants.join(", ")}`
			: "declared but unused";

	if (repo.type === "s3") {
		const region = repo.region
			? `\n      <str name="s3.region">${escapeXml(repo.region)}</str>`
			: "";
		const endpoint = repo.endpoint
			? `\n      <str name="s3.endpoint">${escapeXml(repo.endpoint)}</str>`
			: "";

		return `    <!-- ${escapeXml(served)}. Credentials come from the AWS credential
         chain in Solr's own environment, never from this file. -->
    <repository name="${escapeXml(repo.name)}"
      class="org.apache.solr.s3.S3BackupRepository">
      <str name="s3.bucket.name">${escapeXml(repo.bucket ?? "")}</str>${region}${endpoint}
    </repository>`;
	}

	return `    <!-- ${escapeXml(served)}. Bind-mounted to the host, which is what
         makes a snapshot outlive "docker compose down -v". -->
    <repository name="${escapeXml(repo.name)}"
      class="org.apache.solr.core.backup.repository.LocalFileSystemRepository"
      default="true">
      <str name="location">${escapeXml(localPath)}</str>
    </repository>`;
}

function escapeXml(value: string): string {
	return value
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

/** Solr modules required by the repositories in this registry. */
export function requiredSolrModules(registry: TenantRegistry): string[] {
	const modules = new Set<string>();
	for (const tenant of registry.tenants) {
		if (tenant.backup.type === "s3") modules.add("s3-repository");
	}
	return [...modules];
}
